# 使用 CocoaPods 官方 CDN，提高 pod 安装和更新速度（无需下载整个 Specs 仓库）
source 'https://cdn.cocoapods.org/'

##忽略.cocoapods中多个specs源引起的警告问题
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'ZHHAlertController_Example' do
  
  # Comment the next line if you don't want to use dynamic frameworks
  # 表示可以使用 swift 的框架
  use_frameworks!
  
  pod 'ZHHAlertController', :path => '../'

  # 调试工具（仅 Debug 下生效）
  pod 'LookinServer', :subspecs => ['Swift'], :configurations => ['Debug']  # 自定义的服务器配置（仅在 Debug 模式下使用）

  target 'ZHHAlertController_Tests' do
    inherit! :search_paths

    
  end
end
